server:
  address: 0.0.0.0
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    master:
      type: com.zaxxer.hikari.HikariDataSource
      name: master
      jdbc-url: jdbc:mysql://127.0.0.1:3307/mall?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password:
    slave1:
      type: com.zaxxer.hikari.HikariDataSource
      name: slave1
      jdbc-url: jdbc:mysql://127.0.0.1:3308/mall?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password:
    slave2:
      type: com.zaxxer.hikari.HikariDataSource
      name: slave2
      jdbc-url: jdbc:mysql://127.0.0.1:3309/mall?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password:

mybatis:
  type-aliases-package: com.tong.mall.mapper
  configuration:
    map-underscore-to-camel-case: true